### PR TITLE
context variable renamed to published_articles

### PR DESCRIPTION
**Pull request by Domchap90**

### CODE REVIEW

**Review by Will-Hoey — COMMENTED** [review]
You will need to update the version number in the pyproject.toml

**Comment by Will-Hoey** [comment]
Whilst this will work, there are cleaner ways to set the context name. Alternatively, I think you may even be able to use `article_list` in the template in the project without making any changes here

**Comment by Domchap90** [comment]
That correct or should it be 1.0.0-beta.2?

**Comment by Will-Hoey** [comment]
> That correct or should it be 1.0.0-beta.2?

The latter

**Review by Will-Hoey — APPROVED** [review]

**Pull request merged**
